os: linux
language: cpp
compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install cmake openscenegraph libopenscenegraph-dev libboost-all-dev

before_script:
 - mkdir build
 - cd build
 - cmake -DBUILD_TESTS ..

script: make

notifications:
 email:
  - github.travisci@gmail.com
 on_success: change
 on_failure: always

#whitelist
branches:
 only:
  - master
  - development
