language: cpp
compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get build-dep cmake openscenegraph libopenscenegraph-dev

before_script:
 - mkdir build
 - cd build
 - cmake ..

script: make

notifications:
 email:
  - acsantome@gmail.com
 on_success: never
 on_failure: always

os: linux

# DO THIS!
# blacklist
#branches:
# except:
#  - legacy
#  - experimental

# whitelist
#branches:
# only:
#  - master
#  - stable